[build]
  command = "astro build"
  functions = "dist/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "astro dev"
  port = 8888
  framework = "astro"
  publish = "dist"