[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["astro"]

[dev]
  command = "astro dev"
  port = 8888
  framework = "astro"
  publish = "dist"