name: merge PR
on: 
  pull_request:
    types:
        - opened
    branches:
        - 'main'
jobs:
    merge_pr:
        timeout-minutes: 2
        if: github.actor == 'github-action[bot]'
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Merge PR
                run: gh pr merge $PR_NUMBER --merge
            -   name: Delete remote branch
                run: |
                    git push origin --delete resume
                env:
                    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                    PR_NUMBER: "${{ github.event.pull_request.number }}"