name: Create PR
on: 
  push:
    branches:
        - 'resume'
    paths:
        - 'public/**.pdf'
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
        -   name: Checkout code
            uses: actions/checkout@v3
        -   name: Create Pull Request
            run: gh pr create -B main -H resume --title '[GITHUB ACTION] Updated Resume' --body 'This PR was created automatically by Github Actions for updated resume file to be merged to main branch' --label gh-resume
            env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"